name: Test

on: [push, pull_request]

jobs:
  test_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Running tests
        run: |
          cd ${{ github.workspace }}
          python3 test.py
